directories:
  output: "videos"
  temporary_storage: ""
tex:
  latex:
    executable: "latex"
    template_file: "tex_template.tex" 
    intermediate_filetype: "dvi"
    text_to_replace: "[tex_expression]"
  xelatex:
    # For ctex, use the following configuration
    executable: "xelatex -no-pdf"
    template_file: "ctex_template.tex"
    intermediate_filetype: "xdv"
    text_to_replace: "[tex_expression]"
  default: "latex"
output:
  frame_rate: 60
  mov_vcodec: "qtrle"
  mp4_vcodec: "libx264"
style:
  background_color: "#222222"
  font: "Consolas"
window:
  position: UR
  monitor: 0