directories:
  output: "videos"
  temporary_storage: ""
tex:
  executable: "latex"
  template_file: "tex_template.tex" 
  intermediate_filetype: "dvi"
  text_to_replace: "[tex_expression]"
  # For ctex, use the following configuration
  # executable: "xelatex -no-pdf"
  # template_file: "ctex_template.tex"
  # intermediate_filetype: "xdv"
  # text_to_replace: "[tex_expression]"
output:
  frame_rate: 60
  mov_vcodec: "qtrle"
  mp4_vcodec: "libx264"
style:
  background_color: "#222222"
  font: "Consolas"
window:
  position: UR
  monitor: 0