directories:
  output: "videos"
  temporary_storage: ""
output:
  frame_rate: 60
  mov_vcodec: "qtrle"
  mp4_vcodec: "libx264"
style:
  background_color: "#222222"
  font: "Consolas"
window:
  position: UR
  monitor: 0